### ISSUE TITLE
Autocomplete not showing up

### ISSUE THREAD

**Issue by aronlmin** [TeamWertarbyte/material-ui-search-bar#25] opened 2017-11-04 00:45 UTC
Doesnt seem to want to show up, not getting any errors, using it the same way the live example shows it, just passing it to a redux action

```javascript
<SearchBar
    dataSource={this.props.searchData}
    hintText='Search by Crew Member'
    onChange={(value) => this.props.searchDataSource([value, value + value, value + value + value])}
    onRequestSearch={() => console.log('onRequestSearch')}
    style={{
        margin: '0 auto',
        maxWidth: '100%'
     }}
 />
```

here is a screen recording

![](http://g.recordit.co/L12GiO4WZF.gif)

**Comment by leMaik** [comment] 2017-11-04 18:18
This might be because we use `onClick` instead of `onTouchTap`, which was changed in material-ui v0.19.x :thinking: Please either update material-ui (recommended) or use material-ui-search-bar@0.3.0 (not recommended).

Unfortunately, we are only able to support the latest (beta) version of material-ui.

**Comment by aronlmin** [comment] 2017-11-06 20:16
unfortunately updating to v0.19.4 didn't do the trick 😕, are you referring to IconButtons? I'm not seeing where the source code is using onClick outside of those components

**Comment by leMaik** [comment] 2017-11-07 08:54
Okay, we will look into this. Please don't close this until it is resolved. :wink:

**Comment by leMaik** [comment] 2017-11-21 11:18
@aronlmin We can't reproduce this, see the demo at https://mui.wertarbyte.com/#!/SearchBar/3

Are you accidentially remounting the component while typing somehow? :thinking:

**Comment by leMaik** [comment] 2018-04-27 12:33
I'll close this since I wasn't able to reproduce this and there was no feedback after several months. Feel free to re-open this with a code snippet that can reproduce this issue. :+1:

**Closed by leMaik** 2018-04-27 12:33 UTC
Labels: invalid
