### ISSUE TITLE
Auto-complete results shows with no data source

### ISSUE THREAD

**Issue by bachrc** [TeamWertarbyte/material-ui-search-bar#13] opened 2017-08-16 17:25 UTC
On the version 0.3.0, I'd like to test the default example without any data sources :

```js
<Col md={12}>
    <SearchBar
        onChange={() => console.log('value')}
        onRequestSearch={() => console.log('onRequestSearch')}
        style={{
            margin: '0 auto'
        }}
    />
</Col>
```

And with this basic example, I still get this

![Example](http://i.imgur.com/FMpPrVp.gif)

Could something be interfering ?

**Comment by leMaik** [comment] 2017-08-16 19:36
Looks like we should only use `AutoComplete` if a `dataSource` is configured. Still a strange issue as the popover shouldn't even open if there are no search results.

**Comment by bachrc** [comment] 2017-08-16 19:38
Isn't it possible to just disable the autocomplete function for the search bar ?

**Comment by leMaik** [comment] 2017-08-16 19:47
No, but it _should_ be disabled when there is no `dataSource` configured. It's a bug.

**Comment by leMaik** [comment] 2017-08-24 08:00
@bachrc I can't reproduce this using the latest version and material-ui v0.19. :open_mouth:

**Comment by leMaik** [comment] 2017-09-21 11:08
@bachrc It's been a few weeks. Are you still having problems with this?

**Comment by leMaik** [comment] 2018-04-27 16:26
It's been a while, I'll close this. Feel free to re-open this issue.

**Closed by leMaik** 2018-04-27 16:26 UTC
Labels: bug
