### ISSUE TITLE
How to fire onRequestSearch

### ISSUE THREAD

**Issue by pankaja92** [TeamWertarbyte/material-ui-search-bar#37] opened 2018-03-07 18:53 UTC
This is my code snippet

```
<SearchBar
    onChange={(search) => this.setState({ search })}
    onRequestSearch={() => this.props.searchValue(this.state.search)}
    style={{
            margin: '0 auto',
            maxWidth: '80%'
               }}
 />
```

How can I fire `onRequestSearch` function? When I enter a text, the search icon disappears and clear icon appears. So how can I fire the function?  If I put another text field in the component without any use( no onChange event or anything) I can run the `onRequestSearch` on **SearchBar** by pressing _Enter_
. But if I remove that text field and press enter when the search bar is filled with a search text, the component re-render without calling `onRequestSearch` . So how can I run the function.

**Comment by leMaik** [comment] 2018-04-27 12:31
I'm afraid this took a while. I'll close this but feel free to re-open if you have further questions.

> But if I remove that text field and press enter when the search bar is filled with a search text, the component re-render without calling onRequestSearch . 

That sounds like a bug in your code, because this component clearly calls onRequestSearch without calling onChange with no text before. Unfortunately, I can't reproduce this. :thinking:

**Closed by leMaik** 2018-04-27 12:31 UTC
